### ISSUE TITLE
Restructuring

### ISSUE THREAD

**Issue by Element118** [KALoneNinja/Evaluation-Extension#11]
I'm thinking about making it easier for people to contribute to this.

1. Separate project requirements for each project.
2. Separate evaluation criteria from evaluation criteria HTML.

Might be cleaner to write the CSS as an actual CSS file, think this might help.
https://stackoverflow.com/questions/11553600/how-to-inject-css-using-content-script-file-in-chrome-extension

**Comment by InHoh** [comment]
I'm sure Lone Ninja means to introduce separate project requirements for each project. But I'm not sure if I understand what you mean by 2, Element118.
I am trying to read up on the safety and security aspects of the app 
https://developer.chrome.com/extensions/security
Seeing that there are already files that need to be allowed, I don't think placing the CSS in a different file means creating new security issues.

**Comment by Element118** [comment]
It's not really security issues but making it more modular so that pull requests on different files can be worked on at the same time.

**Comment by KALoneNinja** [comment]
Thanks for that CSS link.
So you mean different files for each project? Correct me if I'm wrong, but to do that I would just add scripts with the src (or href?) specified to each project, and inside each file declare a function for the project which can be called.

**Comment by Element118** [comment]
What I intend this to be is for it to be modular enough so that someone working on project requirements doesn't need to be bogged down by CSS and HTML.

**Comment by KALoneNinja** [comment]
Okay, it is done. The new files I added are where you add all of the messages and stuff.

Examples can be found at the bottom of the file or in the magic 8 ball file

If you want anything changed, let me know.
