### ISSUE TITLE
Error message  "You have not selected all of the pass or fail boxes!" when all boxes are selected

### ISSUE THREAD

**Issue by InHoh** [KALoneNinja/Evaluation-Extension#12]
After the code was changed to ensure messages were not generated until all visible boxes were ticked before generating feedback, I cannot generate feedback in the project under the code, which should be passed. I believe "Generates an even distribution of random numbers, using floor() with random()." is covered.
 //generate feedback
                $("#feedback-generation-btn").on("click", function(){
                    
                    //if the pass/fail are selected _qch9n6d is the class for a passed button
                    if($("._qch9n6d") !== undefined && $("._qch9n6d").length === 6){
                        $("#feedback-generation-click_response").text("");
                        projects[projectType].generateFeedback();
Example:  https://www.khanacademy.org/computer-programming/spin-off-of-project-magic-8-ball/4529757922983936

**Comment by InHoh** [comment]
I have confirmed that the issue is the same with the newest version for this project too. https://www.khanacademy.org/computer-programming/spin-off-of-project-magic-8-ball/5861469992058880

The evaluation can be sent, because the program auto-ticks the box for a pass on "Generates an even distribution..."

**Comment by KALoneNinja** [comment]
Ugh, KA changed the messages, they got rid of the floor(random()) bit! I'll fix it.

**Comment by InHoh** [comment]
No, now I see what happened too. They did not "get rid of" the message. These are old projects that were dumped in the queue, which happens at times. This means there need to be a date check for when the project was submitted. If before, say Nov. 10th 2019 you should simply give a warning that the extension does not work and prevent it from generating anything but praise - or that will be the easiest way out.

**Comment by KALoneNinja** [comment]
Oh, of course!
