### ISSUE TITLE
Text if failed for at least two else could be more specific.

### ISSUE THREAD

**Issue by InHoh** [KALoneNinja/Evaluation-Extension#16]
Current text:

> else is an important tool for coders. It can make our jobs easier with less code to write, but more importantly it makes things much more efficient. This is why it is important for you to prove that you know how to use it here. If you forgot how to use else, make sure to review the tutorials.

Suggested change:
Perhaps you are unsure of what 'mutually exclusive conditions' means? It means that you can never have more than one of the conditions be true when you test it. When your 'answer' is 1, it cannot also be 4. It is inefficient to keep checking other values as your program does. If you have forgotten how to use else (which includes else if), and why, make sure to review the tutorials. The requirement for "at least two else" means that you need at least three conditionals to pass, not that you should skip on "else if" when you have extra conditionals.

Normally I don't like to make the texts longer, but here I believe it cannot be helped. I know there are many younger and ELLs students who simply don't understand the term "mutually exclusive' and what it entails. This project has the highest reading level requirement in Intro to JS, so a large number of students are unable to follow the instructions without help.

Not including enough else if's is one of the more common errors here.

You can include the link to the relevant article, if/else part 2 https://www.khanacademy.org/computing/computer-programming/programming/logic-if-statements/pt/ifelse-part-2

**Comment by KALoneNinja** [comment]
How is this:

oneFeed[1].value = "\"else (if)\" is an important tool for coders. It can make our jobs easier with less code to write, but more importantly it makes \"mutually exclusive conditions\". That means that you can never have more than one of the conditions be true when you test it. When your 'answer' is 1, it cannot also be 4. It is inefficient to keep checking other values as your program does without else. The requirement for \"at least two else\" means that you need at least three conditionals to pass, not that you should skip on \"else if\" when you have extra conditionals. If you have forgotten how to use else (which includes else if), and why, make sure to review the tutorials:\nhttps://www.khanacademy.org/computing/computer-programming/programming/logic-if-statements/pt/ifelse-part-2";

**Comment by InHoh** [comment]
It's not correct that else(if) "makes" mutually exclusive conditions. It's the more effective tool for the situation when you have that kind of conditions, but using it where the conditionals are not exclusive is a logic error.
I don't see how it will make the code much shorter? The only thing you'll be able to skip is the ('answer' === 4) for the last condition, and with else, else you save about 5 characters. If you have more conditionals you don't save anything.

**Comment by KALoneNinja** [comment]
Doesn't it make mutually exclusive conditions though? I agree that it is definitely the best choice to use for it.

It depends what you use it for. Say you didn't make the numbers whole and used < you would save a lot of code.

if(answer < 1){}
else if(answer < 2){}
else if(answer < 3){}
...

rather than
if(answer < 1){}
if(answer >= 1 && answer < 2){}
if(answer >= 2 && answer < 3){}
...

**Comment by KALoneNinja** [comment]
I added your response, thanks!
