### ISSUE TITLE
Suggested message for failed "Contains if/else statements ...:

### ISSUE THREAD

**Issue by InHoh** [KALoneNinja/Evaluation-Extension#17]
The full requirement:
Contains if/else statements that check whether the answer variable exactly equals a certain number.

Suggested message The check for 'exactly equal' is ===. You need to use this in every statement. The only possible exception would be if you make the last statement an 'else' and not 'else if'.

**Comment by KALoneNinja** [comment]
So, is it worth it or not worth it to still include a message of coding simplicity?

**Comment by InHoh** [comment]
Quite a few of the students who make this mistake have removed floor and not replaced it by round. For those students it makes perfectly sense to use <==. I was trying to come up with a short reply that could apply to a larger number of cases,and be combined with a message about the situation where they have not made a fair die. When using the extension I often find myself in a situation where the suggested text does not quite fit. It is hard to think of all the possible reasons for the mistakes, but if we can come up with a reply which does not require the evaluator to regularly have to delete a part of the feedback I think that's good. The reply will still be miles better than a fail with no explanation, and it is fairly easy to add more comments if they seem to fit. My thoughts about it may have been shaped by the number of students who delivered very poor projects in November and December.  I'd like to ask Jonathan's advice on a good number of responses, seeing he has a way of expressing things clearly in few words without sounding terse - a skill I don't have! He does not need to be asked to install the files to read the responses.

**Comment by KALoneNinja** [comment]
I see, that makes sense. I will change it.
