### ISSUE TITLE
TL;DR code triggered by not ticking the box They used something from the documentation

### ISSUE THREAD

**Issue by InHoh** [KALoneNinja/Evaluation-Extension#19]
On the difference between giving a man a fish, and teaching him to fish...
The feedback generated frequently runs more than a screen long, and that is far too much. One contribution to the length is this:

"It would have been great to have seen you go to the documentation and use something from there. Experimentation is a really big part of programming, and the more you experiment right now, the better you will be prepared for the future. On this project, it would have been very beneficial for you to have looked at the text section of the documentation. Instead of doing something like:
```if (answer === 1){
    text("IN", 176, 200);
    text("YOUR DREAMS", 159, 229);
}else if (answer === 2){
    text("NOT", 176, 200);
    text("HAPPENING", 159, 229);
}```
You can just do:
```textAlign(CENTER, CENTER);
if (answer === 1){
    text("IN\nYOUR DREAMS", 200, 200);
}else if (answer === 2){
    text("NOT\nHAPPENING", 200, 200);
}```
See how useful that was?"

I suggest the following change to the text:
Experimentation is an important part of programming. At this point the Documentation tab under your coding window is your best friend. The text section contains other text functions, like textAlign, which can be used to center text. 
Tip: introduce a line break in a text string with \n

**Comment by KALoneNinja** [comment]
Thanks, what do you think about stressing that learning to read documentations is a skill they will always use? ", and other documentations will continue to be throughout your career"

extraSuggestions += "\n\nExperimentation is an important part of programming. At this point the Documentation tab under your coding window is your best friend, and other documentations will continue to be throughout your career. The text section contains other text functions, like textAlign, which can be used to center text.\nTip: introduce a line break in a text string with \\n (see an example in the textLeading() part of documentation)";

**Comment by InHoh** [comment]
I'm a little dubious about stressing their career, as most of the students won't go on to study CS. I think it adds to the length without being important. I'm also painfully aware that a number of the students who are using KA to learn about programming don't have a chance to go off KA for other resources.

**Comment by KALoneNinja** [comment]
Okay, sounds good.
