### ISSUE TITLE
Use GitHub releases for version history

### ISSUE THREAD

**Issue by JettBurns14** [KALoneNinja/Evaluation-Extension#2]
Hey, I noticed you have a version history in the README. GitHub has a feature called releases **just for this purpose**, and they're easy to use after you make a few!

1. Go to your project's [releases](https://github.com/KALoneNinja/Evaluation-Extension/releases), and click "Draft a new release".

2. Now you need to type in a "tag" (like v0.3.4 or v0.9 or v1.5). I'd suggest going back and typing "0.1.0", which is your first version in the README.

3. Next, click on a target next to the tag, and click "Recent commits". Scroll through all your commits, and pick the one that you think v0.1.0 was at.

4. Now add the release title and description.

5. And publish!

You can see the new releases back at the [releases page](https://github.com/KALoneNinja/Evaluation-Extension/releases).

This process will create releases for some commits in the past, but you can do the same as you add new commits to the repo that should go in a new version.

Hope this is helpful and useful! I'd recommend trying it out, it's way easier to keep track of than in the README. Let me know if you have any questions.

More info [here](https://help.github.com/en/github/administering-a-repository/creating-releases).

**Comment by KALoneNinja** [comment]
Thanks! That is a much better way.
