### ISSUE TITLE
Spelling mistake in line 277 Please don't plagiarize...

### ISSUE THREAD

**Issue by InHoh** [KALoneNinja/Evaluation-Extension#22]
oneFeed[1].value = "Link:\nPlease don't plagiarize, you will waste all of our time. You won't learn what you should, and I will be kept away from other projects that are actually proving something. Not to mention it is rude to te author.";

The message has "te author" instead of "the author".
I would suggest changing the text a bit.
oneFeed[1].value = "Link:\nPlease don't plagiarize, it's a waste of time. You won't learn what you should, and I will be kept away from projects that deserve feedback. It is also rude to the author.";

**Comment by KALoneNinja** [comment]
Thanks, I will fix it shortly.
