### ISSUE TITLE
Line 268 if you ever need help, button name

### ISSUE THREAD

**Issue by InHoh** [KALoneNinja/Evaluation-Extension#23]
oneFeed[1].value = "If you ever need help, you can find it in the help requests tab beneath your program. Just post a comment there, and you should get some good help within a day.";

It's not really a tab, it's a button. (I know the two may look the same to a user, but the element is definitely a button, and since this is about learning programming I think it's best to use the correct name. The text on the button is Request help, and it will be easier for the student if it is referred to by that name.
Suggested new line
oneFeed[1].value = "If you ever need help, you can use the Request help button beneath your program. Just post a message explaining the issue there, following instructions in https://www.khanacademy.org/computing/computer-programming/programming/becoming-a-community-coder/a/ask-for-program-help ";

I would not promise a quick response, because while most students will get their response quickly not all get a response.

**Comment by InHoh** [comment]
However, since most projects failed for logic and syntax error will feature Error buddy, I'm not sure pointing them to the Help forum is the best answer.

**Comment by KALoneNinja** [comment]
Well, if Oh Noes can't help them then they should be pointed to people who can explain better. I will add the changes shortly.
