### ISSUE TITLE
Security issues inherent in the project, with respect to recommendations for KA students

### ISSUE THREAD

**Issue by InHoh** [KALoneNinja/Evaluation-Extension#25]
I've looked into things, and gotten some feedback from more knowledgeable people. The gist of it: "Better safe than sorry."
I'm happy to help develop your project in whichever way I can, but I cannot recommend this kind of extension to anyone, including DGPE students, nor help spread the program. 

Most likely the practical outcome is that I'll try to make a web page with the ability to generate the messages based on user input, much like this one, but which does not inject the answers in the field. A bookmarklet might be possible, but this program is rather large for a bookmarklet, and I'm not sure how easy it would be to convert it.

**Comment by KALoneNinja** [comment]
Hmm okay. What are the security issues?

**Comment by InHoh** [comment]
The security issues are inherent in any program which needs to be downloaded from an external source and stored on the computer somehow. 
As pr.Guardian advice, suggesting that students do something Chrome warns against would not be a good policy - even if they do so themselves, I risk it myself, and any student who go beyond the basics taught at KA will probably do, sooner or later. 
I'm simply too closely associated with KA in most students' minds not to have to think twice about what I suggest :-/

**Comment by KALoneNinja** [comment]
I see, would making it an actual extension be any better?

**Comment by InHoh** [comment]
They would still have to upload files from an "unvetted" source (not just you but also whatever storage you used.) So I believe it would still be an issue. I don't know enough about the possibility of locking a version of the program to changes (is the version I download the same as the one by the same version number I saw yesterday), or what might be sent which was not part of that locked file, so I may have to ask again when the extension exists.

**Comment by KALoneNinja** [comment]
No need to keep this up.  I also got rid of every .html command, so it is even more secure now.
