### ISSUE TITLE
Stray "!" if no app field is selected

### ISSUE THREAD

**Issue by InHoh** [KALoneNinja/Evaluation-Extension#26]
Occasionally I come across a program which does not indent the code, does not have sections separated by blank lines, has not used anything from the documentation etc. When this happens, the first feedback line will be "!"
It might be better to dispense with it, or possibly start with "I like your " and let the student finish. The latter is risky, though. The evaluator may not realize that they need to fill it in.

**Comment by KALoneNinja** [comment]
I believe I fixed this.

**Comment by InHoh** [comment]
https://www.khanacademy.org/computer-programming/spin-off-of-project-magic-8-ball/5433436904112128
This student has made one change to the project: The original text is
replaced. I have not ticked any boxes than  Contains if/else statements
that check whether the answer variable exactly equals a certain number.
"There is no if statement for a value of 'answer'.
Suggestion started with !

**Comment by KALoneNinja** [comment]
I am having a hard time replicating this problem, could you explain more?

I do see that sometimes there are line breaks when there shouldn't be.

**Comment by KALoneNinja** [comment]
I think this is satisfied now.
