### ISSUE TITLE
Selecting "They've used something from the documentation" triggers praise for using comments

### ISSUE THREAD

**Issue by InHoh** [KALoneNinja/Evaluation-Extension#3]
Since the program does not register that "They've used something from the documentation" was selected, the auto-generated text also suggests that they use the documentation.
Cause, I believe:
Comments and documentation have changed place in the JS code so that checkBox[1] is linked to Comments and checkBox[2] is linked to Documents,
//checkboxes for general feedback
 and the append checks have Documentation before Comments.

**Comment by KALoneNinja** [comment]
Fixed!
