### ISSUE TITLE
The Generate feedback button does not work if the active tab is Documentation rather than About

### ISSUE THREAD

**Issue by InHoh** [KALoneNinja/Evaluation-Extension#30]
This is not a huge problem, but I sometimes consult the Documentation while giving an evaluation. If I do, I need to reset the tab to About in order to generate the messages.

**Comment by KALoneNinja** [comment]
So, my program accesses the author's name, and the project name through the text below the program for ease and in an attempt to reduce the reliance on API. When the documentation is selected, that text does not exist. I will add an alert to the user to be in the about section when this error occurs.
