### ISSUE TITLE
No message offered after selecting certain boxes

### ISSUE THREAD

**Issue by InHoh** [KALoneNinja/Evaluation-Extension#31]
https://www.khanacademy.org/computer-programming/spin-off-of-project-magic-8-ball/4563138478620672
Uses at least two else statements to check mutually exclusive conditions (not just if statements).
Shows a different message for each if statement and possible value of the answer variable (where each message must differ more than just displaying the different value of answer).
selected They used indents
No text was offered.

May or may not be related to error message I found in the extension
Uncaught TypeError: Cannot read property 'innerText' of undefined
Kontekst
content.js:175 (anonym funksjon)

**Comment by KALoneNinja** [comment]
It could be the issue I brought up before. I only have help buttons for bubbles that have text in them. The problem there is that the check box is found with an index and that messes it up. I was going to fix it by going back from the length.

**Comment by InHoh** [comment]
I have figured out something that definitely triggers that error message and the lack of generated text.
https://www.khanacademy.org/computer-programming/magic-8-ball/5687069675634688
has two conditionals with the same text, so neither of the check boxes fit. When I say that there is an error in the code, and don't select any of the boxes the error is triggered and no automatically generated message appears.

**Comment by KALoneNinja** [comment]
I think I fixed it, let me know if it isn't.
