### ISSUE TITLE
Nice Job should not have a capital in Job.

### ISSUE THREAD

**Issue by InHoh** [KALoneNinja/Evaluation-Extension#4]
The code is "$("textarea.discussion-text.eval-text")[0].value += "Nice Job " + projectOwner + "! " + "Congratulations on completing " + projectType + "!\n-_ " + evaluationAuthor + " (with help of Auto Feedback Generator Extension_";"
"

var finalFeed = $("textarea.discussion-text.eval-text");
--
finalFeed[finalFeed.length-1].value += "Nice Job " + projectOwner + "! " + extraCompliments + "!" + extraSuggestions + "\n\nKeep up the hard work! - " + evaluationAuthor + " (with help of Feedback Generator Extension[testing][version: 0.5.1])";
"
Additionally I would strongly suggest adding a conditional so that "Nice job" was only added "if(pass)".  Sometimes a project is well worthy of praise even if they don't pass, but I would rather just praise them specifically for what is good than implying they did a good job submitting a project full of errors...

**Comment by KALoneNinja** [comment]
Fixed both concerns.
