### ISSUE TITLE
Generation of the "I evaluated your project" message

### ISSUE THREAD

**Issue by InHoh** [KALoneNinja/Evaluation-Extension#6]
In Magic 8 ball it seems as if two buttons will generate this message automatically:
 if(checkBoxes[3].checked){ // - IH: that's line breaks, and 
if(checkBoxes[4].checked){ // -IH: that's use of comments

"$("._qwk47qNaN")[0].value = "Hi! I evaluated your project. If you have any questions, thoughts, want some advice, or want any projects evaluated, you can contact me here.";
"
But this message should probably be generated at least for each fail, and possible for all projects.
Not all students will want to leave contact information so I think it's good that the message is only being offered, and that you have to specifically send it. I was a little surprised that it shows up in both the Questions box and the Tips and thanks box, because we definitely don't want those to go in the questions forum, and Questions is the first one to be offered.

**Comment by KALoneNinja** [comment]
That is interesting that it goes in both, it seems they must use the same class name or something. Ill also want to see if I can switch tabs so you don't have to.

**Comment by KALoneNinja** [comment]
I don't have time to check if I fixed it right now, but hopefully it is fixed!

**Comment by KALoneNinja** [comment]
Okay, it is not possible to only post a message in one of the boxes, try typing a message yourself and changing tabs. It stays there.. I can try to change the tab though.

**Comment by KALoneNinja** [comment]
As far as I can tell it isn't possible.
