### ISSUE TITLE
Error message  “Couldn't find a project. Try using YAPEP (in resources)” confusing

### ISSUE THREAD

**Issue by InHoh** [KALoneNinja/Evaluation-Extension#7]
The idea is that the student should open a project using YAPEP before pressing the Evaluate button on the project, so I'd like to see that spelled out more clearly.
"Could not find a project. Select a student's project in YAPEP (in Resources) and click the Evaluate this project button" seems better to me because I expected to be offered a new button and the same window as before.

**Comment by KALoneNinja** [comment]
Fixed

**Comment by KALoneNinja** [comment]
Fixed
